defaults:
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

max_time: 10.0

data:
  n_coils: 1
  smaps: false
  dtype: complex64

trajectory: "./trajs/radial_256x256_0.5.bin"
task:
  - forward
  - adjoint
  - grad

backend:
  name: finufft
  eps: 1e-3
  upsampfac: 2.0

monitor:
  interval: 0.5
  gpu: true

hydra:
  job:
    chdir: true
  run:
    dir: outputs/new_/${now:%Y-%m-%d}/${backend.name}_${now:%H-%M-%S}/
  sweep:
    dir: outputs/new_/3D/${now:%Y-%m-%d}/${backend.name}_${now:%H-%M-%S}/

